//#line 2 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the monoslam_ros_test package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __monoslam_ros_test__STATEESTIMATIONPARAMSCONFIG_H__
#define __monoslam_ros_test__STATEESTIMATIONPARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace monoslam_ros_test
{
  class StateestimationParamsConfigStatics;
  
  class StateestimationParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(StateestimationParamsConfig &config, const StateestimationParamsConfig &max, const StateestimationParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const StateestimationParamsConfig &config1, const StateestimationParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, StateestimationParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const StateestimationParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, StateestimationParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const StateestimationParamsConfig &config) const = 0;
      virtual void getValue(const StateestimationParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T StateestimationParamsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (StateestimationParamsConfig::* field);

      virtual void clamp(StateestimationParamsConfig &config, const StateestimationParamsConfig &max, const StateestimationParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const StateestimationParamsConfig &config1, const StateestimationParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, StateestimationParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const StateestimationParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, StateestimationParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const StateestimationParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const StateestimationParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, StateestimationParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, StateestimationParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<StateestimationParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(StateestimationParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("UseControlGains"==(*i)->name){UseControlGains = boost::any_cast<bool>(val);}
        if("UseNavdata"==(*i)->name){UseNavdata = boost::any_cast<bool>(val);}
        if("UsePTAM"==(*i)->name){UsePTAM = boost::any_cast<bool>(val);}
        if("PTAMMapLock"==(*i)->name){PTAMMapLock = boost::any_cast<bool>(val);}
        if("PTAMSyncLock"==(*i)->name){PTAMSyncLock = boost::any_cast<bool>(val);}
        if("PTAMMaxKF"==(*i)->name){PTAMMaxKF = boost::any_cast<int>(val);}
        if("PTAMMinKFDist"==(*i)->name){PTAMMinKFDist = boost::any_cast<double>(val);}
        if("PTAMMinKFWiggleDist"==(*i)->name){PTAMMinKFWiggleDist = boost::any_cast<double>(val);}
        if("PTAMMinKFTimeDiff"==(*i)->name){PTAMMinKFTimeDiff = boost::any_cast<double>(val);}
        if("RescaleFixOrigin"==(*i)->name){RescaleFixOrigin = boost::any_cast<bool>(val);}
        if("c1"==(*i)->name){c1 = boost::any_cast<double>(val);}
        if("c2"==(*i)->name){c2 = boost::any_cast<double>(val);}
        if("c3"==(*i)->name){c3 = boost::any_cast<double>(val);}
        if("c4"==(*i)->name){c4 = boost::any_cast<double>(val);}
        if("c5"==(*i)->name){c5 = boost::any_cast<double>(val);}
        if("c6"==(*i)->name){c6 = boost::any_cast<double>(val);}
        if("c7"==(*i)->name){c7 = boost::any_cast<double>(val);}
        if("c8"==(*i)->name){c8 = boost::any_cast<double>(val);}
      }
    }

    bool UseControlGains;
bool UseNavdata;
bool UsePTAM;
bool PTAMMapLock;
bool PTAMSyncLock;
int PTAMMaxKF;
double PTAMMinKFDist;
double PTAMMinKFWiggleDist;
double PTAMMinKFTimeDiff;
bool RescaleFixOrigin;
double c1;
double c2;
double c3;
double c4;
double c5;
double c6;
double c7;
double c8;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool UseControlGains;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool UseNavdata;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool UsePTAM;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool PTAMMapLock;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool PTAMSyncLock;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int PTAMMaxKF;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double PTAMMinKFDist;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double PTAMMinKFWiggleDist;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double PTAMMinKFTimeDiff;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool RescaleFixOrigin;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c2;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c3;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c4;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c5;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c6;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c7;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double c8;
//#line 255 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("StateestimationParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const StateestimationParamsConfig &__max__ = __getMax__();
      const StateestimationParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const StateestimationParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const StateestimationParamsConfig &__getDefault__();
    static const StateestimationParamsConfig &__getMax__();
    static const StateestimationParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const StateestimationParamsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void StateestimationParamsConfig::ParamDescription<std::string>::clamp(StateestimationParamsConfig &config, const StateestimationParamsConfig &max, const StateestimationParamsConfig &min) const
  {
    return;
  }

  class StateestimationParamsConfigStatics
  {
    friend class StateestimationParamsConfig;
    
    StateestimationParamsConfigStatics()
    {
StateestimationParamsConfig::GroupDescription<StateestimationParamsConfig::DEFAULT, StateestimationParamsConfig> Default("Default", "", 0, 0, true, &StateestimationParamsConfig::groups);
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.UseControlGains = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.UseControlGains = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.UseControlGains = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("UseControlGains", "bool", 0, "Use Control Commands for prediction in EKF", "", &StateestimationParamsConfig::UseControlGains)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("UseControlGains", "bool", 0, "Use Control Commands for prediction in EKF", "", &StateestimationParamsConfig::UseControlGains)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.UseNavdata = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.UseNavdata = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.UseNavdata = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("UseNavdata", "bool", 0, "Enable EKF-Updates from Navdata", "", &StateestimationParamsConfig::UseNavdata)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("UseNavdata", "bool", 0, "Enable EKF-Updates from Navdata", "", &StateestimationParamsConfig::UseNavdata)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.UsePTAM = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.UsePTAM = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.UsePTAM = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("UsePTAM", "bool", 0, "Enable EKF-Updates from PTAM", "", &StateestimationParamsConfig::UsePTAM)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("UsePTAM", "bool", 0, "Enable EKF-Updates from PTAM", "", &StateestimationParamsConfig::UsePTAM)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.PTAMMapLock = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.PTAMMapLock = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.PTAMMapLock = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("PTAMMapLock", "bool", 0, "Lock PTAM Map (take no more KF)", "", &StateestimationParamsConfig::PTAMMapLock)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("PTAMMapLock", "bool", 0, "Lock PTAM Map (take no more KF)", "", &StateestimationParamsConfig::PTAMMapLock)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.PTAMSyncLock = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.PTAMSyncLock = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.PTAMSyncLock = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("PTAMSyncLock", "bool", 0, "Lock PTAM <-> EKF sync (fix scale & offsets)", "", &StateestimationParamsConfig::PTAMSyncLock)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("PTAMSyncLock", "bool", 0, "Lock PTAM <-> EKF sync (fix scale & offsets)", "", &StateestimationParamsConfig::PTAMSyncLock)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.PTAMMaxKF = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.PTAMMaxKF = 1000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.PTAMMaxKF = 200;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<int>("PTAMMaxKF", "int", 0, "Max. Number of KF (1 => inf)", "", &StateestimationParamsConfig::PTAMMaxKF)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<int>("PTAMMaxKF", "int", 0, "Max. Number of KF (1 => inf)", "", &StateestimationParamsConfig::PTAMMaxKF)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.PTAMMinKFDist = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.PTAMMinKFDist = 5.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.PTAMMinKFDist = 0.4;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("PTAMMinKFDist", "double", 0, "Min. new KF distance in meters (only works properly after scale init)", "", &StateestimationParamsConfig::PTAMMinKFDist)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("PTAMMinKFDist", "double", 0, "Min. new KF distance in meters (only works properly after scale init)", "", &StateestimationParamsConfig::PTAMMinKFDist)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.PTAMMinKFWiggleDist = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.PTAMMinKFWiggleDist = 10.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.PTAMMinKFWiggleDist = 0.075;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("PTAMMinKFWiggleDist", "double", 0, "Min. new KF distance relative to mean scene depth.", "", &StateestimationParamsConfig::PTAMMinKFWiggleDist)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("PTAMMinKFWiggleDist", "double", 0, "Min. new KF distance relative to mean scene depth.", "", &StateestimationParamsConfig::PTAMMinKFWiggleDist)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.PTAMMinKFTimeDiff = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.PTAMMinKFTimeDiff = 10.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.PTAMMinKFTimeDiff = 0.5;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("PTAMMinKFTimeDiff", "double", 0, "Min. time between taking two KF in seconds", "", &StateestimationParamsConfig::PTAMMinKFTimeDiff)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("PTAMMinKFTimeDiff", "double", 0, "Min. time between taking two KF in seconds", "", &StateestimationParamsConfig::PTAMMinKFTimeDiff)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.RescaleFixOrigin = 0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.RescaleFixOrigin = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.RescaleFixOrigin = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("RescaleFixOrigin", "bool", 0, "on scale reestimation: if TRUE, the map init pos remains fixed, if false, the current drone pos remains fixed.", "", &StateestimationParamsConfig::RescaleFixOrigin)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<bool>("RescaleFixOrigin", "bool", 0, "on scale reestimation: if TRUE, the map init pos remains fixed, if false, the current drone pos remains fixed.", "", &StateestimationParamsConfig::RescaleFixOrigin)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c1 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c1 = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c1 = 0.58;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c1", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c1", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c1)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c2 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c2 = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c2 = 17.5;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c2", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c2", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c2)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c3 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c3 = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c3 = 7.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c3", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c3", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c3)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c4 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c4 = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c4 = 24.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c4", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c4)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c4", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c4)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c5 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c5 = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c5 = 25.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c5", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c5)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c5", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c5)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c6 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c6 = 200.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c6 = 90.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c6", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c6)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c6", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c6)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c7 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c7 = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c7 = 0.8;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c7", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c7)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c7", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c7)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.c8 = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.c8 = 50.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.c8 = 0.6;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c8", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c8)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(StateestimationParamsConfig::AbstractParamDescriptionConstPtr(new StateestimationParamsConfig::ParamDescription<double>("c8", "double", 0, "prediction model parameter", "", &StateestimationParamsConfig::c8)));
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(StateestimationParamsConfig::AbstractGroupDescriptionConstPtr(new StateestimationParamsConfig::GroupDescription<StateestimationParamsConfig::DEFAULT, StateestimationParamsConfig>(Default)));
//#line 390 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<StateestimationParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<StateestimationParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<StateestimationParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    StateestimationParamsConfig __max__;
    StateestimationParamsConfig __min__;
    StateestimationParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const StateestimationParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static StateestimationParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &StateestimationParamsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const StateestimationParamsConfig &StateestimationParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const StateestimationParamsConfig &StateestimationParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const StateestimationParamsConfig &StateestimationParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<StateestimationParamsConfig::AbstractParamDescriptionConstPtr> &StateestimationParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<StateestimationParamsConfig::AbstractGroupDescriptionConstPtr> &StateestimationParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const StateestimationParamsConfigStatics *StateestimationParamsConfig::__get_statics__()
  {
    const static StateestimationParamsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = StateestimationParamsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __STATEESTIMATIONPARAMSRECONFIGURATOR_H__
