(cl:in-package monoslam_ros_test-msg)
(cl:export '(HEADER-VAL
          HEADER
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          DX-VAL
          DX
          DY-VAL
          DY
          DZ-VAL
          DZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          DYAW-VAL
          DYAW
          SCALE-VAL
          SCALE
          PTAMSTATE-VAL
          PTAMSTATE
          SCALEACCURACY-VAL
          SCALEACCURACY
          DRONESTATE-VAL
          DRONESTATE
          BATTERYPERCENT-VAL
          BATTERYPERCENT
))